import { useEffect, useRef, useState } from 'react';
import { Camera, RotateCcw, Upload, X } from 'lucide-react';
import type { MathDeskImage } from '../types/ai';

interface CameraCaptureProps { onClose: () => void; onUseImage: (image: MathDeskImage & { preview: string }) => void; }

export default function CameraCapture({ onClose, onUseImage }: CameraCaptureProps) {
  const videoRef = useRef<HTMLVideoElement>(null); const canvasRef = useRef<HTMLCanvasElement>(null); const streamRef = useRef<MediaStream | null>(null); const fileRef = useRef<HTMLInputElement>(null); const [facing, setFacing] = useState<'environment' | 'user'>('environment'); const [captured, setCaptured] = useState<string | null>(null); const [error, setError] = useState('');
  async function startCamera(nextFacing = facing) { setError(''); try { streamRef.current?.getTracks().forEach((track) => track.stop()); const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: nextFacing }, width: { ideal: 1920 }, height: { ideal: 1080 } }, audio: false }); streamRef.current = stream; if (videoRef.current) { videoRef.current.srcObject = stream; await videoRef.current.play(); } } catch (cameraError) { const name = cameraError instanceof DOMException ? cameraError.name : ''; setError(name === 'NotAllowedError' ? 'Camera permission was denied. You can upload a photo instead.' : name === 'NotFoundError' ? 'No camera was found on this device.' : 'We could not access the camera. You can upload a photo instead.'); } }
  useEffect(() => { if (!navigator.mediaDevices?.getUserMedia) { setError('This browser does not support camera capture. You can upload a photo instead.'); } else void startCamera(); return () => { streamRef.current?.getTracks().forEach((track) => track.stop()); }; }, []);
  function close() { streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current = null; onClose(); }
  function capture() { const video = videoRef.current; const canvas = canvasRef.current; if (!video || !canvas || !video.videoWidth) return; canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext('2d')?.drawImage(video, 0, 0, canvas.width, canvas.height); setCaptured(canvas.toDataURL('image/jpeg', .92)); }
  function useCaptured() { if (!captured) return; onUseImage({ mimeType: 'image/jpeg', data: captured.split(',')[1], preview: captured }); close(); }
  function handleUpload(file?: File) { if (!file || !file.type.startsWith('image/')) return; const reader = new FileReader(); reader.onload = () => { const preview = String(reader.result); onUseImage({ mimeType: file.type, data: preview.split(',')[1], preview }); close(); }; reader.readAsDataURL(file); }
  return <div className="camera-overlay" role="dialog" aria-modal="true" aria-labelledby="camera-title"><section className="camera-card"><header className="camera-header"><div><span className="eyebrow"><Camera size={14} /> Camera input</span><h2 id="camera-title">Capture a math problem</h2></div><button className="tool-close" onClick={close} aria-label="Close camera"><X size={18} /></button></header><div className="camera-view">{captured ? <img src={captured} alt="Captured math problem preview" /> : <video ref={videoRef} autoPlay playsInline muted />}{error && <div className="camera-error"><Camera size={25} /><p>{error}</p><button className="primary-tool-button" onClick={() => fileRef.current?.click()}><Upload size={15} /> Upload a photo</button></div>}</div><canvas ref={canvasRef} hidden /><input ref={fileRef} type="file" accept="image/*" hidden onChange={(event) => handleUpload(event.target.files?.[0])} /><footer className="camera-actions">{captured ? <><button className="secondary-tool-button" onClick={() => setCaptured(null)}><RotateCcw size={15} /> Retake</button><button className="primary-tool-button" onClick={useCaptured}>Use this photo</button></> : <>{!error && <><button className="camera-flip" onClick={() => { const next = facing === 'environment' ? 'user' : 'environment'; setFacing(next); void startCamera(next); }} title="Switch camera">↻</button><button className="capture-button" onClick={capture} aria-label="Capture photo"><span /></button></>}<button className="secondary-tool-button" onClick={() => fileRef.current?.click()}><Upload size={15} /> Upload instead</button></>}</footer></section></div>;
}
