import { useEffect, useRef, useState } from 'react';
import { Eraser, PenLine, RotateCcw, Send, Trash2, X } from 'lucide-react';
import type { MathDeskImage } from '../types/ai';

interface HandwritingCanvasProps { onClose: () => void; onUseImage: (image: MathDeskImage & { preview: string }) => void; }
export default function HandwritingCanvas({ onClose, onUseImage }: HandwritingCanvasProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const drawing = useRef(false); const [tool, setTool] = useState<'pen' | 'eraser'>('pen'); const [size, setSize] = useState(4);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const context = canvas.getContext('2d'); if (!context) return; const ratio = window.devicePixelRatio || 1; const width = Math.min(canvas.parentElement?.clientWidth || 700, 760); const height = Math.min(window.innerHeight * .52, 430); canvas.width = width * ratio; canvas.height = height * ratio; canvas.style.width = `${width}px`; canvas.style.height = `${height}px`; context.scale(ratio, ratio); context.lineCap = 'round'; context.lineJoin = 'round'; context.fillStyle = '#fff'; context.fillRect(0, 0, width, height); }, []);
  function point(event: React.PointerEvent<HTMLCanvasElement>) { const rect = event.currentTarget.getBoundingClientRect(); return { x: event.clientX - rect.left, y: event.clientY - rect.top }; }
  function start(event: React.PointerEvent<HTMLCanvasElement>) { event.preventDefault(); const context = canvasRef.current?.getContext('2d'); if (!context) return; drawing.current = true; const p = point(event); context.beginPath(); context.moveTo(p.x, p.y); event.currentTarget.setPointerCapture(event.pointerId); }
  function move(event: React.PointerEvent<HTMLCanvasElement>) { if (!drawing.current) return; event.preventDefault(); const context = canvasRef.current?.getContext('2d'); if (!context) return; const p = point(event); context.globalCompositeOperation = tool === 'eraser' ? 'destination-out' : 'source-over'; context.strokeStyle = '#17265d'; context.lineWidth = tool === 'eraser' ? size * 3 : size; context.lineTo(p.x, p.y); context.stroke(); }
  function stop() { drawing.current = false; }
  function clear() { const canvas = canvasRef.current; const context = canvas?.getContext('2d'); if (canvas && context) { context.globalCompositeOperation = 'source-over'; context.fillStyle = '#fff'; context.fillRect(0, 0, canvas.width, canvas.height); } }
  function useDrawing() { const canvas = canvasRef.current; if (!canvas) return; const preview = canvas.toDataURL('image/png'); onUseImage({ mimeType: 'image/png', data: preview.split(',')[1], preview }); onClose(); }
  return <div className="tool-modal-overlay"><section className="draw-card" role="dialog" aria-modal="true" aria-labelledby="draw-title"><header className="tool-modal-header"><div><span className="eyebrow"><PenLine size={14} /> Tablet-friendly input</span><h2 id="draw-title">Handwrite a problem</h2></div><button className="tool-close" onClick={onClose} aria-label="Close handwriting canvas"><X size={18} /></button></header><div className="draw-toolbar"><button className={tool === 'pen' ? 'active' : ''} onClick={() => setTool('pen')}><PenLine size={15} /> Pen</button><button className={tool === 'eraser' ? 'active' : ''} onClick={() => setTool('eraser')}><Eraser size={15} /> Eraser</button><label>Size <input type="range" min="2" max="10" value={size} onChange={(event) => setSize(Number(event.target.value))} /></label><button onClick={clear}><Trash2 size={15} /> Clear</button></div><div className="draw-surface"><canvas ref={canvasRef} onPointerDown={start} onPointerMove={move} onPointerUp={stop} onPointerCancel={stop} onPointerLeave={stop} /></div><footer className="draw-actions"><button className="secondary-tool-button" onClick={onClose}><RotateCcw size={15} /> Cancel</button><button className="primary-tool-button" onClick={useDrawing}><Send size={15} /> Use in chat</button></footer></section></div>;
}
