import { useEffect, useState } from 'react';
import { BookOpen, Cloud, FileText, Plus, Trash2, X } from 'lucide-react';
import { loadLocalLessons, saveLocalLesson, deleteLocalLesson, syncLessons, type SavedLesson } from '../services/lessons';

interface LessonLibraryProps { onClose: () => void; initialContent?: string; }
export default function LessonLibrary({ onClose, initialContent = '' }: LessonLibraryProps) {
  const [lessons, setLessons] = useState<SavedLesson[]>([]); const [title, setTitle] = useState(''); const [content, setContent] = useState(initialContent); const [notice, setNotice] = useState('');
  useEffect(() => { setLessons(loadLocalLessons()); syncLessons().then(setLessons).catch(() => setNotice('Cloud sync is unavailable. Your local lessons remain safe on this device.')); }, []);
  function save() { if (!title.trim() || !content.trim()) { setNotice('Add a title and lesson content first.'); return; } const lesson = saveLocalLesson({ title: title.trim(), content: content.trim(), source_type: 'text' }); setLessons((current) => [lesson, ...current]); setTitle(''); setContent(''); setNotice('Saved locally. It will sync when your account and connection are available.'); }
  function remove(lesson: SavedLesson) { if (lesson.id) deleteLocalLesson(lesson.id); setLessons((current) => current.filter((item) => item !== lesson)); }
  return <div className="tool-modal-overlay"><section className="lessons-card" role="dialog" aria-modal="true" aria-labelledby="lessons-title"><header className="tool-modal-header"><div><span className="eyebrow"><BookOpen size={14} /> Your learning library</span><h2 id="lessons-title">Saved lessons</h2></div><button className="tool-close" onClick={onClose} aria-label="Close saved lessons"><X size={18} /></button></header><div className="lesson-form"><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Lesson title" /><textarea value={content} onChange={(event) => setContent(event.target.value)} placeholder="Paste lesson text, notes, or a solved explanation…" rows={4} /><button className="primary-tool-button" onClick={save}><Plus size={15} /> Save lesson</button></div>{notice && <p className="lesson-notice" role="status"><Cloud size={14} /> {notice}</p>}<div className="lesson-list">{lessons.length === 0 && <p className="empty-tools">No saved lessons yet. Save notes here to use them across your study sessions.</p>}{lessons.map((lesson, index) => <article className="lesson-item" key={lesson.id || `${lesson.title}-${index}`}><FileText size={18} /><div><strong>{lesson.title}</strong><p>{lesson.content.slice(0, 120)}{lesson.content.length > 120 ? '…' : ''}</p><small>{lesson.synced ? 'Synced to your account' : 'Saved on this device'}</small></div><button onClick={() => remove(lesson)} aria-label={`Delete ${lesson.title}`}><Trash2 size={15} /></button></article>)}</div></section></div>;
}
